### ISSUE TITLE
✨ Reactions panel ads removal

### ISSUE THREAD

**Issue by N-coder82** [AushevAhmad/awesome-css#2]
### Feature Request Description

Please remove the ads for when you try to react with a nitro emoji and discord does a popup, remove the other emojis from the reaction panel whatsoever please.

### Screenshots

![CleanShot 2024-04-03 at 07 37 49@2x](https://github.com/AushevAhmad/awesome-css/assets/80474621/48b70b3f-5bf7-492a-843f-d46f40e8c9ab)

### Final Checks

- [X] My issue title is descriptive
- [X] This is a single feature request (multiple feature requests should be reported individually)

**Comment by AushevAhmad** [comment]
I tried to remove ad when you try to react with a custom emoji while not having nitro, but because I don't have that purple lock panel and "Unlock these emoji with Nitro" ad I can't remove, I basically don't have that pushed, it's either an experiment either something else...

**Comment by N-coder82** [comment]
ahh ok
